# Домашнее задание по лекции "Библиотека numpy. Вычислительные задачи."

Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [70]:
import numpy as np

try: 
    num = int(input('Введите число N: '))
    if num > 0:
        x = np.arange(num-1, -1,-1)
        
    elif num < 0:
            x = np.arange(num+1, 1,1)
    
    elif num == 0:
            x = None
    
    print(x)
    
except: print('что-то пошло не так')


Введите число N: 0
None


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [63]:
num = int(input('Введите число N: '))


x = np.eye(num+1)
print(x)
print('*********************************')
y = np.arange(num, -1,-1)
print(y)
print('*********************************')
z = x*y
print(z)
print()
print('Сумма элементов ' + str(z.sum()))

Введите число N: 4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
*********************************
[4 3 2 1 0]
*********************************
[[4. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]

Сумма элементов 10.0


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [55]:
from numpy import linalg

# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4] ] )
# значения в правой части уравнения
b = np.array( [4, 12, -3] )
print(linalg.solve(a, b))
np.allclose( np.dot(a, linalg.solve(a, b)), b )

[ 0.46666667  3.84444444 -5.55555556]


True